# These are supported funding model platforms

github: veteran29
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: veteran29
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://www.paypal.me/veteran29
